[tool.poetry]
name = "ocpvtk"
version = "0.1.0"
description = "Python wheels for OCP (OpenCascade Python wrapper)"
authors = [ "fpq473", "roipoussiere" ]

[tool.poetry.dependencies]
python = "^3.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
