name: Create Python wheel using Conda

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        # os: [ "ubuntu", "macos", "windows" ]
        os: [ "ubuntu" ]
        python-version: [ "3.9" ]

    steps:

      - name: Checkout project (to retrieve setup.py)
        uses: actions/checkout@v2

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          python-version: ${{ matrix.python-version }}
          environment-file: env.yml
          channels: conda-forge
          activate-environment: cadquery
          auto-activate-base: false

      - name: Info
        run: |
          conda info
          conda list

      # - name: Install cibuildwheel
      #   shell: bash -l {0}
      #   run: python -m pip install cibuildwheel==2.4.0

      - name: Build wheels
        shell: bash -l {0}
        run: |
          conda install -y ocp=7.5.3.0
          python -m pip install --upgrade pip
          python -m pip install auditwheel build
          python -m build --no-isolation
        # python -m cibuildwheel --output-dir dir

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ocpvtk-wheel
          path: dist
