name: Create Python wheel using Conda

on:
	push:
		branches: [ master ]

jobs:
	build:

		strategy:
			matrix:
				os: [ ubuntu-latest, windows-latest, macos-latest ]

		runs-on: ${{ matrix.os }}
			steps:
			- uses: actions/checkout@v3
			- uses: actions/setup-python@v3
				with:
					python-version: 3.9

			# Download Miniforge
			- name: Download Miniforge3 on Linux
				if: matrix.os == 'ubuntu-latest'
				run: |
				  wget -O Miniforge3.sh "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
					bash Miniforge3.sh -b -u
			- name: Download Miniforge3 on MacOS
				if: matrix.os == 'macos-latest'
				run: |
				  wget -O Miniforge3.sh "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-$(uname -m).sh"
					bash Miniforge3.sh -b -u
			- name: Download Miniforge3 on Windows
				if: matrix.os == 'windows-latest'
				run: |
				  Invoke-WebRequest -Uri "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Windows-x86_64.exe" -OutFile "Miniforge3.exe"
					start /wait "" Miniforge3.exe /InstallationType=JustMe /RegisterPython=0 /S /D=%UserProfile%\Miniforge3
