name: Create Python wheel using Conda

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        # os: [ "ubuntu", "macos", "windows" ]
        os: [ "ubuntu" ]
        python-version: [ "3.9" ]

    steps:

      - name: Checkout project
        uses: actions/checkout@v2

      # see https://cibuildwheel.readthedocs.io/en/stable/
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.4.0
        with:
          output-dir: dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ocpvtk-wheel
          path: dist

      # see https://github.com/marketplace/actions/pypi-publish
      - name: Publish to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
