name: Create Python wheel using Conda

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        # os: [ "ubuntu", "macos", "windows" ]
        os: [ "ubuntu" ]
        python-version: [ "3.9" ]

    steps:

      - name: Checkout project
        uses: actions/checkout@v2

      # see https://github.com/marketplace/actions/setup-miniconda
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          activate-environment: cadquery
          python-version: ${{ matrix.python-version }}
          channels: conda-forge

      - name: Print info
        shell: bash -l {0}
        run: |
          conda info
          conda list

      - name: Install OCP
        shell: bash -l {0}
        run: conda install -n cadquery -y ocp=7.5.3.0

      - name: Build wheels (ubuntu)
        if: ${{ matrix.os }} == "ubuntu"
        shell: bash -l {0}
        run: |
          pip install --upgrade pip
          pip install auditwheel build
          python -m build --no-isolation

      - name: Build wheels (macos)
        if: ${{ matrix.os }} == "macos"
        shell: bash -l {0}
        run: |
          pip install --upgrade pip
          pip install delocate build
          python -m build --no-isolation

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ocpvtk-wheel
          path: dist

      # see https://github.com/marketplace/actions/pypi-publish
      - name: Publish to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
