name: Create Python wheel using Conda

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        # os: [ "ubuntu", "macos", "windows" ]
        os: [ "ubuntu" ]
        python-version: [ "3.9" ]

    steps:

      - name: Checkout project
        uses: actions/checkout@v2

      # see https://github.com/marketplace/actions/setup-miniconda
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          activate-environment: cadquery
          python-version: ${{ matrix.python-version }}
          environment-file: env.yml
          channels: conda-forge
          auto-activate-base: false

      - name: Print info
        run: |
          conda info
          conda list

      # # see https://cibuildwheel.readthedocs.io/en/stable/
      # - name: Install cibuildwheel
      #   shell: bash -l {0}
      #   run: python -m pip install cibuildwheel==2.4.0

      - name: Build wheels
        run: |
          conda install -y ocp=7.5.3.0
          $CONDA/bin/pip install --upgrade pip
          $CONDA/bin/pip install auditwheel build
          $CONDA/bin/python -m build --no-isolation
        # python -m cibuildwheel --output-dir dir

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ocpvtk-wheel
          path: dist

      # # see https://github.com/marketplace/actions/pypi-publish
      # - name: Publish to PyPI
      #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     user: __token__
      #     password: ${{ secrets.PYPI_API_TOKEN }}
