name: Create Python wheel using Conda

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: [ "ubuntu", "macos", "windows" ]
        python-version: [ "3.9" ]

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          activate-environment: cadquery
          python-version: ${{ matrix.python-version }}
          # channels: conda-forge
          environment-file: env.yml
      - name: Conda install
        run: conda install -y ocp=7.5.3.0
      - name: Pip install
        run: |
          pip install --upgrade pip
          pip install auditwheel build
      - name: Python build
        run: python -m build --no-isolation
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ocpvtk-wheel
          path: dist
