name: Create Python wheel using Conda

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        # os: [ "ubuntu", "macos", "windows" ]
        os: [ "ubuntu" ]
        python-version: [ "3.9" ]

    steps:

      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          auto-activate-base: true
          auto-update-conda: true
          activate-environment: true

      - name: Info
        run: |
          which python
        # conda info
        # conda list

      # - name: Install cibuildwheel
      #   run: $CONDA/bin/python -m pip install cibuildwheel==2.4.0

      # - name: Build wheels
      #   run: |
      #     conda install -y ocp=7.5.3.0
      #     python -m cibuildwheel --output-dir dist

      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: ocpvtk-wheel
      #     path: dist
