name: Create Python wheel using Conda

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: [ "ubuntu", "macos", "windows" ]
        python-version: [ "3.9" ]

    steps:

      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          activate-environment: cadquery

      - name: Info
        run: |
          which python
          conda info
          conda list

      - name: Python build on Linux and Mac
        if: matrix.os != 'windows'
        shell: bash -l {0}
        run: |
          conda install -y ocp=7.5.3.0
          $CONDA/bin/pip install --upgrade pip
          $CONDA/bin/pip install auditwheel build
          $CONDA/bin/python -m build --no-isolation

      - name: Python build on Windows
        if: matrix.os == 'windows'
        shell: pwsh
        run: |
          conda install -y ocp=7.5.3.0
          $CONDA/bin/pip install --upgrade pip
          $CONDA/bin/pip install auditwheel build
          $CONDA/bin/python -m build --no-isolation

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ocpvtk-wheel
          path: dist
