name: Releases

on: 
  push:
    tags: [ '*' ]

jobs:

  release:
    name: Pubish release
    runs-on: ubuntu-latest
    steps:

      # see https://github.com/marketplace/actions/download-workflow-artifact
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build_wheel.yml
          path: wheels

      # Remove this after next ocp build
      # see https://github.com/roipoussiere/OCP/commit/e38eecd4ca5f9071c189fda0dd78893c50b3bc7c
      - name: Move wheels
        run: |
          mkdir dist
          mv wheels/**/*.whl dist
          rm -rf wheels
          ls dist

      # see https://github.com/marketplace/actions/create-release
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.whl"
          token: ${{ secrets.GITHUB_TOKEN }}

      # see https://github.com/marketplace/actions/pypi-publish
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
