name: Releases
# https://github.com/marketplace/actions/automatic-releases
# https://github.com/marketplace/actions/publish-release
# https://github.com/marketplace/actions/create-release
# https://github.com/marketplace/actions/github-release

on: 
  push:
    tags: [ '*' ]

jobs:

  build:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: write
    steps:

    # - uses: actions/checkout@v2
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build_wheel.yml
        path: wheels
        # check_artifacts: true

    - name: Display info
      run: ls wheels

    # https://github.com/marketplace/actions/create-release
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "wheels/*.whl"
        token: ${{ secrets.GITHUB_TOKEN }}

      # # see https://github.com/marketplace/actions/pypi-publish
      # - name: Publish to PyPI
      #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags') && matrix.os == 'ubuntu'
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     user: __token__
      #     password: ${{ secrets.PYPI_API_TOKEN }}
